# Copyright 2024 Advanced Micro Devices, Inc.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: CI - sharktuner

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/ci-sharktuner.yml'
      - 'sharktuner/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci-sharktuner.yml'
      - 'sharktuner/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.10.12'

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r sharktuner/requirements-dev.txt

      - name: Install sharktuner dependencies
        run: |
          pip install -r requirements-iree-unpinned.txt
          pip install -r sharktuner/requirements.txt
          pip install --no-compile \
            -r sharktuner/requirements-tests.txt \
            -e sharktuner/

          pip freeze

      - name: Run sharktuner tests
        run: pytest sharktuner/

      - name: Run mypy type checker
        run: mypy sharktuner/sharktuner
